--
-- PostgreSQL database dump
--

\restrict cEdNjYG77oO8LNcBNxlkn7ZeELCUqNmx9pJKh1pyK2uiCufPCo6cr4GjGUY8MND

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-16 23:16:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE IF EXISTS bluemoon_db;
--
-- TOC entry 5090 (class 1262 OID 16387)
-- Name: bluemoon_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE bluemoon_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


ALTER DATABASE bluemoon_db OWNER TO postgres;

\unrestrict cEdNjYG77oO8LNcBNxlkn7ZeELCUqNmx9pJKh1pyK2uiCufPCo6cr4GjGUY8MND
\connect bluemoon_db
\restrict cEdNjYG77oO8LNcBNxlkn7ZeELCUqNmx9pJKh1pyK2uiCufPCo6cr4GjGUY8MND

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 16474)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    password character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    role_id bigint NOT NULL,
    resident_id bigint
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16473)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16389)
-- Name: billing_period; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.billing_period (
    id bigint NOT NULL,
    closed boolean,
    end_date date,
    month integer NOT NULL,
    start_date date,
    year integer NOT NULL
);


ALTER TABLE public.billing_period OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16388)
-- Name: billing_period_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.billing_period ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.billing_period_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16398)
-- Name: fee_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fee_category (
    id bigint NOT NULL,
    active boolean,
    code character varying(50) NOT NULL,
    default_amount numeric(15,2),
    description character varying(255),
    fixed_monthly boolean,
    name character varying(100) NOT NULL,
    unit character varying(50)
);


ALTER TABLE public.fee_category OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16397)
-- Name: fee_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fee_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16407)
-- Name: household; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.household (
    id bigint NOT NULL,
    active boolean,
    apartment_number character varying(20) NOT NULL,
    created_at timestamp(6) without time zone,
    household_code character varying(50) NOT NULL,
    members_count integer,
    move_in_date date,
    move_out_date date,
    owner_name character varying(100) NOT NULL,
    phone character varying(20),
    residence_status character varying(50),
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.household OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16417)
-- Name: household_fee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.household_fee (
    id bigint NOT NULL,
    amount numeric(15,2),
    due_date date,
    quantity numeric(15,2),
    status character varying(20),
    unit_price numeric(15,2),
    billing_period_id bigint NOT NULL,
    fee_category_id bigint NOT NULL,
    household_id bigint NOT NULL
);


ALTER TABLE public.household_fee OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16416)
-- Name: household_fee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.household_fee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.household_fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16406)
-- Name: household_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.household ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.household_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16427)
-- Name: payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment (
    id bigint NOT NULL,
    amount numeric(15,2) NOT NULL,
    method character varying(50),
    note character varying(255),
    paid_at timestamp(6) without time zone,
    household_fee_id bigint NOT NULL
);


ALTER TABLE public.payment OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16426)
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16436)
-- Name: resident; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resident (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    date_of_birth date,
    full_name character varying(100) NOT NULL,
    gender character varying(10),
    id_number character varying(50),
    phone character varying(20),
    relation_to_head character varying(50),
    residence_status character varying(50),
    updated_at timestamp(6) without time zone,
    household_id bigint NOT NULL
);


ALTER TABLE public.resident OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16435)
-- Name: resident_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 16487)
-- Name: role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.role OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 16486)
-- Name: role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5082 (class 0 OID 16474)
-- Dependencies: 232
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.account VALUES (2, '2025-07-12 00:00:00', 'admin123', '2025-07-12 00:00:00', 'admin01', 2, NULL) ON CONFLICT DO NOTHING;
INSERT INTO public.account VALUES (1, '2025-07-12 00:00:00', '123456', '2025-07-12 00:00:00', 'resident01', 1, 1) ON CONFLICT DO NOTHING;


--
-- TOC entry 5070 (class 0 OID 16389)
-- Dependencies: 220
-- Data for Name: billing_period; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5072 (class 0 OID 16398)
-- Dependencies: 222
-- Data for Name: fee_category; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5074 (class 0 OID 16407)
-- Dependencies: 224
-- Data for Name: household; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.household VALUES (1, true, 'A101', '2025-12-01 19:14:06.189838', 'H001', 3, NULL, NULL, 'Nguyen Van A', '0123456789', 'DANG_O', '2025-12-01 19:14:06.189838') ON CONFLICT DO NOTHING;


--
-- TOC entry 5076 (class 0 OID 16417)
-- Dependencies: 226
-- Data for Name: household_fee; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5078 (class 0 OID 16427)
-- Dependencies: 228
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 5080 (class 0 OID 16436)
-- Dependencies: 230
-- Data for Name: resident; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.resident VALUES (1, '2025-08-12 00:00:00', '2024-12-08', 'Nguyen Hoang Long', 'Nam', '1', '0403043043', 'Con', 'Active', '2025-08-12 00:00:00', 1) ON CONFLICT DO NOTHING;


--
-- TOC entry 5084 (class 0 OID 16487)
-- Dependencies: 234
-- Data for Name: role; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role VALUES (1, 'RESIDENT') ON CONFLICT DO NOTHING;
INSERT INTO public.role VALUES (2, 'ADMIN') ON CONFLICT DO NOTHING;


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 231
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 5, true);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 219
-- Name: billing_period_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.billing_period_id_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 221
-- Name: fee_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.fee_category_id_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 225
-- Name: household_fee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.household_fee_id_seq', 1, false);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 223
-- Name: household_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.household_id_seq', 1, true);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 227
-- Name: payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_id_seq', 1, false);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 229
-- Name: resident_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.resident_id_seq', 1, false);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 233
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.role_id_seq', 8, true);


--
-- TOC entry 4908 (class 2606 OID 16482)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 16396)
-- Name: billing_period billing_period_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.billing_period
    ADD CONSTRAINT billing_period_pkey PRIMARY KEY (id);


--
-- TOC entry 4894 (class 2606 OID 16405)
-- Name: fee_category fee_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_category
    ADD CONSTRAINT fee_category_pkey PRIMARY KEY (id);


--
-- TOC entry 4902 (class 2606 OID 16425)
-- Name: household_fee household_fee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household_fee
    ADD CONSTRAINT household_fee_pkey PRIMARY KEY (id);


--
-- TOC entry 4898 (class 2606 OID 16415)
-- Name: household household_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household
    ADD CONSTRAINT household_pkey PRIMARY KEY (id);


--
-- TOC entry 4904 (class 2606 OID 16434)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- TOC entry 4906 (class 2606 OID 16443)
-- Name: resident resident_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resident
    ADD CONSTRAINT resident_pkey PRIMARY KEY (id);


--
-- TOC entry 4914 (class 2606 OID 16493)
-- Name: role role_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.role
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 4896 (class 2606 OID 16445)
-- Name: fee_category ukcje94bhnudyq3m0dlt24spiqc; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fee_category
    ADD CONSTRAINT ukcje94bhnudyq3m0dlt24spiqc UNIQUE (code);


--
-- TOC entry 4910 (class 2606 OID 16484)
-- Name: account ukgex1lmaqpg0ir5g1f5eftyaa1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukgex1lmaqpg0ir5g1f5eftyaa1 UNIQUE (username);


--
-- TOC entry 4912 (class 2606 OID 16500)
-- Name: account ukjxtwetrowtd365oi8hnb1dyud; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT ukjxtwetrowtd365oi8hnb1dyud UNIQUE (resident_id);


--
-- TOC entry 4900 (class 2606 OID 16447)
-- Name: household ukkueevo1w3qbwt7v37r0ubscax; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household
    ADD CONSTRAINT ukkueevo1w3qbwt7v37r0ubscax UNIQUE (household_code);


--
-- TOC entry 4915 (class 2606 OID 16448)
-- Name: household_fee fk2l2gie0wfmb53l58g5pni2f6y; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household_fee
    ADD CONSTRAINT fk2l2gie0wfmb53l58g5pni2f6y FOREIGN KEY (billing_period_id) REFERENCES public.billing_period(id);


--
-- TOC entry 4916 (class 2606 OID 16458)
-- Name: household_fee fkbdprusbndfac0qpcd60eojld2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household_fee
    ADD CONSTRAINT fkbdprusbndfac0qpcd60eojld2 FOREIGN KEY (household_id) REFERENCES public.household(id);


--
-- TOC entry 4920 (class 2606 OID 16494)
-- Name: account fkd4vb66o896tay3yy52oqxr9w0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fkd4vb66o896tay3yy52oqxr9w0 FOREIGN KEY (role_id) REFERENCES public.role(id);


--
-- TOC entry 4921 (class 2606 OID 16501)
-- Name: account fke6rxsgkrycgbwvkke4ds50fs5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fke6rxsgkrycgbwvkke4ds50fs5 FOREIGN KEY (resident_id) REFERENCES public.resident(id);


--
-- TOC entry 4917 (class 2606 OID 16453)
-- Name: household_fee fkl75df66mfilu2lyq5omxvrbg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.household_fee
    ADD CONSTRAINT fkl75df66mfilu2lyq5omxvrbg FOREIGN KEY (fee_category_id) REFERENCES public.fee_category(id);


--
-- TOC entry 4919 (class 2606 OID 16468)
-- Name: resident fklaf6ipjvwblhj9mp9bn8wp2ba; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resident
    ADD CONSTRAINT fklaf6ipjvwblhj9mp9bn8wp2ba FOREIGN KEY (household_id) REFERENCES public.household(id);


--
-- TOC entry 4918 (class 2606 OID 16463)
-- Name: payment fko1sfg9eyh2835bmgxblu5m38i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fko1sfg9eyh2835bmgxblu5m38i FOREIGN KEY (household_fee_id) REFERENCES public.household_fee(id);


-- Completed on 2025-12-16 23:16:37

--
-- PostgreSQL database dump complete
--

\unrestrict cEdNjYG77oO8LNcBNxlkn7ZeELCUqNmx9pJKh1pyK2uiCufPCo6cr4GjGUY8MND

